### ISSUE TITLE
Stratum Crash

### ISSUE THREAD

**Issue by cryptowhizzard** [globalzon/yaamp#26]
08:38:55: invalid json: {"result":{"version":8196,"previousblockhash":"e20d8a13bf157a4e9e235732aca7f8e521e5e1c747cd7ccfab177edf79065c32","transactions":[{"data":"010000004f509a5a0105b3890372af35f15c501cc2841fda379e7e6ee7a9c115f02fc2ef4e4cfc68cf000000006b483045022010bb45d738bcb87bfe352c787e4a157f9e949fe7205bdc61e5fd56ae7d45212602210091b8dbd3f2d9f995e7c77a793949af699736a8b885f501f82c59f08c317121e0012102a40fa63d04fe37531c89b03f98ee1999a312a718a729db97068127c85401747effffffff02a0e05f4e2b0000001976a914d28544e470dc97bc9e4dbaae31a088ecac63fce588ac8d08e4870b0000001976a9144f8684778b464dddf8bfd7f7e905cbfe406f84ae88ac00000000","hash":"6e959fba038ecf0c094637bd3ac1960b941f0edad912fe890c7a244ee91b35e6","fee":1000000,"depends":[],"sigops":2},{"data":"010000006f509a5a06f1b5d7981e08f7b92f1997bc972a2e313bd0a5515b8506dcc6cbdf826fe75ade000000006c493046022100d7ac068db0e2009f0170660cb74076d85da9c7da8ebdcd6bff7cc208aa430ed5022100e20b4167fc12cf215b554f7e604824c195fe149a8d0338ac80f055814b80664a012103d621b5ab5341727183338e9c17ae3c47e9e55d0c64a06b7a63b136a00f58e2feffffffff587813548b29cc9eabd04b21a79278a041c677f833d08d888c187f682e216b754a0000006c493046022100d09d29758b0cc9f2a3ab7f6dedbe98ec7877e8541d454e9b223d7ef522f99e2c022100de2047ae32760be30fcfb758832b43206263efea8b592fd31771d12170e9aa470121036f5a7151f8e5f1a1c8ba3fac6ed12f519714967227343816e2bffb3f0c255bc6ffffffff2c738e6343aca86ee57305acabebaed4f638908210ab83ebb0227f95fd66e55f010000006b483045022044416e359a76e5023aa33f595503ba2f50b39966de9907a6a75a9c598a8f7f88022100efcb4be26c2d62cf33f5f8542fdc103d6db5cccd5268e0b2c43e7879b70f1f8401210223a03993f6760e882ec757192f11bcbfc2b5ca85766e4d0eae1fb9a1cf61f645fffffffffe48c0fc460fe16e69115b46803c71b26cd57b1badc5100c24f57e873295abcb010000006c493046022100e64804d11744fb424a781bfe5068ad06108ea8aafbad5fa093766103913cd352022100d3c8cf8fa9cb573305eb992844035bd7c9aa8e70595cbf24ff0b6026e524fdf8012102e208e13964ef7117e8f20aebcf3745d0c0cd29fbf6a177c5c748b6f1bb7f7a20ffffffff752d82deb0e58626529ee921a41b05065fbfdec94f1ef854226866db9ed4dafc360000006c493046022100ff8bd40999a8ea9b7a0af4238096efb628bbb87179331405aba38245becc8cd0022100865a69825aad21f6d03dc269632727ea84c4608d9e233076f7356b82e8ecabb701210359b5b89da8da273da65e70d847c16e853bbda609d15285c6a032cedcb19a41b0fffffffff1a6fc73ceb69406c54f3fc22cded3be8cc4532487cf035119152d358c5f978a690000006a4730440220129bc0c20d62d37a53823727870e4cf12a62d173ddd6c7282cc9688c55830688022043e9a94071b8562de87f80ce30e811daceefd82ae3c6d8ac076ac1c37c9ed965012103bd4ade68c178e5d621eb03ba92b91c9f9b7f423755975c30345f12c2a75f9298ffffffff0144d60a13000000001976a914b9e21744ddf7a8e4ad88029fa6230364eaa9308288ac00000000","hash":"933c2f0bcdec7ccdb4e8549e5c88ce77ba4f9a997d047e2954b4fc062a539e26","fee":200000,"depends":[],"sigops":1}],"coinbaseaux":{"flags":"062f503253482f"},"coinbasevalue":1561200000,"target":"0000000000000198670000000000000000000000000000000000000000000000","mintime":1520062609,"mutable":["time","transactions","prevblock"],"noncerange":"00000000ffffffff","sigoplimit":20000,"sizelimit":1000000,"curtime":1520062621,"bits":"1a019867","height":1923610},"error":null,"id":"1"}
HTTP/1.1 500 Internal Server Error
Date: Sat, 03 Mar 2018 07:38:55 +0000
Connection: close
Content-Length: 74
Content-Type: application/json
Server: VERGE-json-rpc/v4.0.1.0-2610206-funky-beta

{"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}
08:38:55: ERROR: recv1, 0, 0, {"method":"validateaddress","params":["<addressfiltered>"],"id":"6"}, 
blake2s, unable to verify XVG address for user coinid 561...
2018-03-03 08:38:55 [ipfilered] addressfiltered, blake2s, bad mining address addressfiltered
tail: /var/stratum/config/blake2s.log: file truncated
08:38:57: 2018-03-03 starting stratum for blake2s on <filteredhostname>:5766
08:38:57: connecting to coind info

**Comment by goodthebest** [comment]
@wijnandschouten still having the same problem? I can work it out, if you are keen you may contact me

**Comment by cryptowhizzard** [comment]
Nope, it's already solved.
